### ISSUE TITLE
No ext/moderngpu found

### ISSUE THREAD

**Issue by shyhuai** [owensgroup/merge-spmm#1]
Dear authors, it seems that the `ext/moderngpu` package was not put in the repository. I compiled the codes, but it said:
"Cannot find source file: /ext/moderngpu/src/mgpucontext.cu".

Could you provide the right position to pull the complete codes? Thanks!

**Comment by ctcyang** [comment]
Hello, thank you for pointing it out! I added the git module in the latest commit. If you already have the cloned repository, then you need to:
```
git submodule init
git submodule update
```

**Comment by shyhuai** [comment]
Thanks! It is solved.
