### ISSUE TITLE
Hello, I couldn't compile modern GPU

### ISSUE THREAD

**Issue by hochawa** [owensgroup/merge-spmm#3]
Hello,

I tried to install merge-spmm based on the instructions provided in README.

But, I failed to install modern GPU as follows.

I am not sure, but password seems to be required to install modern GPU.

Could you tell me how can I resolve this issue?

Thank you!

Regards,
Changwan Hong

----------------------------------------
[hongc@cerberus mgpu]$ git clone --recursive https://github.com/owensgroup/GraphBLAS.git
Initialized empty Git repository in /home/hongc/carl_spmm/mgpu/GraphBLAS/.git/
remote: Enumerating objects: 230, done.
remote: Counting objects: 100% (230/230), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 4005 (delta 135), reused 141 (delta 66), pack-reused 3775
Receiving objects: 100% (4005/4005), 5.13 MiB, done.
Resolving deltas: 100% (2690/2690), done.
Submodule 'ext/cub' (https://ctcyang@github.com/NVlabs/cub.git) registered for path 'ext/cub'
Submodule 'ext/moderngpu' (https://ctcyang@github.com/ctcyang/moderngpu.git) registered for path 'ext/moderngpu'
Initialized empty Git repository in /home/hongc/carl_spmm/mgpu/GraphBLAS/ext/cub/.git/
Password:
remote: Enumerating objects: 32642, done.
remote: Total 32642 (delta 0), reused 0 (delta 0), pack-reused 32642
Receiving objects: 100% (32642/32642), 16.49 MiB | 24.46 MiB/s, done.
Resolving deltas: 100% (28621/28621), done.
Password:
Submodule path 'ext/cub': checked out 'd622848f9fb62f13e5e064e1deb43b6bcbb12bad'
Initialized empty Git repository in /home/hongc/carl_spmm/mgpu/GraphBLAS/ext/moderngpu/.git/
Password:
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 1664 (delta 13), reused 15 (delta 6), pack-reused 1639
Receiving objects: 100% (1664/1664), 6.81 MiB, done.
Resolving deltas: 100% (952/952), done.
Password:
Submodule path 'ext/moderngpu': checked out '9e491c383e935c2cbc0279350640dad3febb8b9d'
[hongc@cerberus mgpu]$ git checkout europar
fatal: Not a git repository (or any of the parent directories): .git
--------------------------------------

**Comment by ctcyang** [comment]
Hi Changwan,

I see your issue. It seems that my instructions left out a line. It says:
```
git clone --recursive https://github.com/owensgroup/GraphBLAS.git
git checkout europar
```
but it should actually be:
```
git clone --recursive https://github.com/owensgroup/GraphBLAS.git
cd GraphBLAS
git checkout europar
```

Maybe you can give that a try and let me know what happens.

**Comment by hochawa** [comment]
Hello Carl,


Thank you for the prompt reply.


Unfortunately, I could not still resolve the issue.


The error message is as follows.


[hongc@cerberus mgpu2]$ git clone --recursive https://github.com/owensgroup/GraphBLAS.git
Initialized empty Git repository in /home/hongc/carl_spmm/mgpu2/GraphBLAS/.git/
remote: Enumerating objects: 233, done.
remote: Counting objects: 100% (233/233), done.
remote: Compressing objects: 100% (165/165), done.
remote: Total 4008 (delta 137), reused 144 (delta 67), pack-reused 3775
Receiving objects: 100% (4008/4008), 5.13 MiB, done.
Resolving deltas: 100% (2692/2692), done.
Submodule 'ext/cub' (https://ctcyang@github.com/NVlabs/cub.git) registered for path 'ext/cub'
Submodule 'ext/moderngpu' (https://ctcyang@github.com/ctcyang/moderngpu.git) registered for path 'ext/moderngpu'
Initialized empty Git repository in /home/hongc/carl_spmm/mgpu2/GraphBLAS/ext/cub/.git/
Password:
remote: Enumerating objects: 32642, done.
remote: Total 32642 (delta 0), reused 0 (delta 0), pack-reused 32642
Receiving objects: 100% (32642/32642), 16.49 MiB | 15.11 MiB/s, done.
Resolving deltas: 100% (28621/28621), done.
Password:
Submodule path 'ext/cub': checked out 'd622848f9fb62f13e5e064e1deb43b6bcbb12bad'
Initialized empty Git repository in /home/hongc/carl_spmm/mgpu2/GraphBLAS/ext/moderngpu/.git/
Password:
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 1664 (delta 13), reused 15 (delta 6), pack-reused 1639
Receiving objects: 100% (1664/1664), 6.81 MiB | 11.80 MiB/s, done.
Resolving deltas: 100% (952/952), done.
Password:
Submodule path 'ext/moderngpu': checked out '9e491c383e935c2cbc0279350640dad3febb8b9d'
[hongc@cerberus mgpu2]$ ls
GraphBLAS
[hongc@cerberus mgpu2]$ cd GraphBLAS/
[hongc@cerberus GraphBLAS]$ git checkout europar
warning: unable to rmdir ext/cub: Directory not empty
M       ext/moderngpu
Branch europar set up to track remote branch europar from origin.
Switched to a new branch 'europar'
[hongc@cerberus GraphBLAS]$ cd ext/moderngpu/
[hongc@cerberus moderngpu]$ ls
benchmarkinsert        benchmarkloadbalance   benchmarkscan       benchmarksort          demo                  moderngpu.sln  testlaunchbox
benchmarkintervalmove  benchmarklocalitysort  benchmarksegreduce  benchmarksortedsearch  include               parallelmerge  testsegsortbyflags
benchmarkjoin          benchmarkmerge         benchmarksegsort    benchmarkspmvcsr       Makefile              README.md      vs.props
benchmarklaunchbox     benchmarkreducebykey   benchmarksets       common.mk              mgpu_benchmarks.xlsx  src
[hongc@cerberus moderngpu]$ git checkout europar
Previous HEAD position was 9e491c3... accidentally deleted KernelIntervalExpand
Branch europar set up to track remote branch europar from origin.
Switched to a new branch 'europar'
[hongc@cerberus moderngpu]$ cd ../..
[hongc@cerberus GraphBLAS]$ ls
blah.txt        dataset  Figure1a-spmm-4.sh  Figure1b.sh  Figure5b.sh  Figure7_genmatrix.sh  gen_matrix.cpp  LICENSE    spmm-europar18-preprint.pdf
CMakeLists.txt  ext      Figure1a-spmv.sh    Figure5a.sh  Figure6.sh   Figure7.sh            graphblas       README.md  test
[hongc@cerberus GraphBLAS]$ cd ext/merge-spmv/
[hongc@cerberus merge-spmv]$ ls
[hongc@cerberus merge-spmv]$ make gpu_spmv sm=350
make: *** No rule to make target `gpu_spmv'.  Stop.




The problem is there are no files at ./ext/merge-spmv


Just in case, I was asked the password when I installed modernGPU as seen above.


Regards,

Changwan Hong

________________________________
보낸 사람: Carl Yang <notifications@github.com>
보낸 날짜: 2018년 10월 31일 수요일 오후 3:45:20
받는 사람: owensgroup/merge-spmm
참조: hochawa; Author
제목: Re: [owensgroup/merge-spmm] Hello, I couldn't compile modern GPU (#3)


Hi Changwan,

I see your issue. It seems that my instructions left out a line. It says:

git clone --recursive https://github.com/owensgroup/GraphBLAS.git
git checkout europar


but it should actually be:

git clone --recursive https://github.com/owensgroup/GraphBLAS.git
cd GraphBLAS
git checkout europar


Maybe you can give that a try and let me know what happens.

**Comment by ctcyang** [comment]
I see the problem you are having. The problem is it says:
```
git clone --recursive https://github.com/owensgroup/GraphBLAS.git
cd GraphBLAS
git checkout europar
```
What it should have said is:
```
git clone --recursive https://github.com/owensgroup/merge-spmm.git
cd merge-spmm
```
Then the next step should work:
```
cd ext/merge-spmv
make gpu_spmv sm=350
cd ../../
```

**Comment by hochawa** [comment]
Thank you for the kind reply.


I am still struggling, but a problem might be my side.


I will let you know if I will be not able to install it.


Take care!


Regards,

Changwan Hong

________________________________
보낸 사람: Carl Yang <notifications@github.com>
보낸 날짜: 2018년 10월 31일 수요일 오후 4:32:25
받는 사람: owensgroup/merge-spmm
참조: hochawa; Author
제목: Re: [owensgroup/merge-spmm] Hello, I couldn't compile modern GPU (#3)


I see the problem you are having. The problem is it says:

git clone --recursive https://github.com/owensgroup/GraphBLAS.git
cd GraphBLAS
git checkout europar


What it should have said is:

git clone --recursive https://github.com/owensgroup/merge-spmm.git
cd merge-spmm


Then the next step should work:

cd ext/merge-spmv
make gpu_spmv sm=350
cd ../../

**Comment by ctcyang** [comment]
Sounds good! Let me know if you run into any issues.

**Comment by hochawa** [comment]
Thank you!


I think everything looks fine.


Actually, I had already installed boost, so I could use boost without your guidance.


Just in case, when I follows the below instructions, there were no files at path/to/installation/prefix (i.e., the directory I wanted to install boost).


Just in case, should the files exist at the path "path/to/installation/prefix"?


I did not raise this issue to github since it may be my fault.



wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz
tar -xvzf boost_1_58_0.tar.gz
cd boost_1_58_0
./bootstrap.sh --prefix=path/to/installation/prefix
./b2 --with-program_options




Regards,
Changwan Hong
________________________________
보낸 사람: Carl Yang <notifications@github.com>
보낸 날짜: 2018년 11월 1일 목요일 오전 2:35:22
받는 사람: owensgroup/merge-spmm
참조: hochawa; Author
제목: Re: [owensgroup/merge-spmm] Hello, I couldn't compile modern GPU (#3)


Sounds good! Let me know if you run into any issues.

**Comment by ctcyang** [comment]
Boost can be challenging to install. I know I've had to spend a good hour getting it to install the first time. What I would do is:
-try to do `sudo ./b2 --with-program_options`. Sometimes, if the [path/to/installation/prefix] is in `/usr/lib`, you need sudo privileges in order to install to there
-if that doesn't work, I would look at the Boost installation documentation. They may give some more help: https://www.boost.org/doc/libs/1_58_0/more/getting_started/unix-variants.html
-if that still doesn't work, I would look at installing using some variant of:
```
sudo apt-get update
sudo apt-get install libboost-dev
```
(This command is for Ubuntu 16.04. You may need to vary the command a bit depending on the OS you have)
