### ISSUE TITLE
May I know where I can download the data sets that were used in your paper

### ISSUE THREAD

**Issue by shyhuai** [owensgroup/merge-spmm#4]
I can download the "large" data set in the folder using the script: ``merge-spmm/dataset/europar/large/DownloadFigure6.sh``, but the ``highd`` and ``lowd`` folders have not such download addresses. Could you provide some help? Thanks!

**Comment by jowens** [comment]
Fairly sure that every matrix we used was from https://sparse.tamu.edu/ ... ?

**Comment by shyhuai** [comment]
Noted with thanks. Could you also provide the file list of the used matrices? Actually, we would like to reproduce the results present in the paper on newer GPUs (e.g., RTX 2080).

**Comment by jowens** [comment]
@ctcyang 's gotta address this one, I'm afraid.

**Comment by ctcyang** [comment]
Hi @shyhuai, I've added the filenames to the two folders `highd` and `lowd`. Now typing `make` under `dataset/europar/highd` or `dataset/europar/lowd` should automatically download all datasets as according to the instructions.

Thanks for letting us know! Please lets us know if you run into any other issues.

**Comment by shyhuai** [comment]
Hi @ctcyang, thank you very much for your support. It works very well to download all the datasets.
