### ISSUE TITLE
Algorithm implementation

### ISSUE THREAD

**Issue by shi27feng** [owensgroup/merge-spmm#9]
Hi @ctcyang,
Hope you are doing well.
I'm wondering which part of the code implementing the function _**PartitionSpmm**_ mentioned in your paper?

Thanks in advance!

**Comment by ctcyang** [comment]
Hi @shi27feng,

The PartitionSpmm function corresponds to [this line](https://github.com/ctcyang/moderngpu/blob/europar/include/kernels/spmvcsr.cuh#L320).
The parallel for loop corresponds to [KernelSpmmCsr kernel](https://github.com/ctcyang/moderngpu/blob/7864935712a5dab71ab19160e160a559f640f4f1/include/kernels/spmvcsr.cuh#L332)
Then the FixCarryOut function corresponds to the [SegReduceSpinePrealloc](https://github.com/ctcyang/moderngpu/blob/7864935712a5dab71ab19160e160a559f640f4f1/include/kernels/spmvcsr.cuh#L530)

Hope that helps. Let me know if you have other questions.

**Comment by shi27feng** [comment]
Thank you very much for the prompt reply!
